# Feishu (Lark)
BASE_URL: https://open.feishu.cn
APP_ID: cli_axxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
# Please ensure this matches the settings in the Feishu application management platform
BOT_NAME: chatGpt
# OpenAI key supports load balancing. You can fill in multiple keys separated by commas
OPENAI_KEY: sk-xxx,sk-xxx,sk-xxx
# OpenAI model - specify the model, default is gpt-3.5-turbo
# Optional parameters include: "gpt-4-1106-preview", "gpt-4-32K", "gpt-4", "gpt-3.5-turbo-16k", "gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-3.5-turbo-1106", etc.
# If using gpt-4, please confirm whether you have API access whitelist
OPENAI_MODEL: gpt-3.5-turbo
# OpenAI maximum token count, default is 2000
OPENAI_MAX_TOKENS: 2000
# Response timeout in milliseconds, default is 550ms
OPENAI_HTTP_CLIENT_TIMEOUT: 550
# Server configuration
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# OpenAI address, generally no need to modify unless you have your own reverse proxy
API_URL: https://api.openai.com
# Proxy settings, e.g., "http://127.0.0.1:7890", "" means no proxy
HTTP_PROXY: ""
# Whether to enable stream mode for interface response
STREAM_MODE: false # set true to use stream mode
# AZURE OPENAI
AZURE_ON: false # set true to use Azure rather than OpenAI
AZURE_API_VERSION: 2023-03-15-preview # 2023-03-15-preview or 2022-12-01 refer https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions
AZURE_RESOURCE_NAME: xxxx   # you can find in endpoint url. Usually looks like https://{RESOURCE_NAME}.openai.azure.com
AZURE_DEPLOYMENT_NAME: xxxx # usually looks like ...openai.azure.com/openai/deployments/{DEPLOYMENT_NAME}/chat/completions.
AZURE_OPENAI_TOKEN: xxxx  # Authentication key. We can use Azure Active Directory Authentication(TBD).

